### ISSUE TITLE
secrets NPM_TOKEN

### ISSUE THREAD

**Issue by Viserion77** [Adapcon/adapcon-utils-js#160]
https://github.com/Adapcon/adapcon-utils-js/blob/f71aa50c4633db1abfbee709f7084b01095e5b7d/.github/workflows/master.yml#L28

Salve galerinha!

Este token esta em meus dominios, seria otimo trocar para a conta da adap no npm:
```
login: adapcon
senha: ta lá na tela de senhas no csw, ou no meu privado :eyes:
```

[Genrete a token on npm](https://www.npmjs.com/settings/adapcon/tokens)

🤘🏼

**Comment by mickaelnn** [comment]
Salve salve, acabei de trocar, Grato
